GridLayout:
    rows:3
    cols:1
    BoxLayout:
        TextInput:
            id: input_number
            text: '7'
            font_size: 48
            multiline: False
        Button:
            text: 'Square'
            on_press: app.handle_calculate()
        Label:
            id: output_label
            font_size: 48
            color: (0, 1, 1, 1)
    BoxLayout:
        Label:
            text:'Enter a number and press "Square"'
